[tool.black]
line-length = 100
target-version = ["py310"]
include = "\.(py|pyi)$"
exclude = [
  "^/\.venv/",
  "^/reports/",
]

[tool.ruff]
line-length = 100
target-version = "py310"
exclude = [".venv", "reports"]
select = [
  "E",  # pycodestyle errors
  "F",  # pyflakes
  "I",  # isort
  "W",  # warnings
  "B",  # bugbear
]
ignore = [
  "E203",  # whitespace before ':' (compat with black)
]

[tool.ruff.isort]
known-first-party = ["optimizer", "monitoring", "Audit"]
combine-as-imports = true

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
