[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"

# API proxy configuration for same-domain deployment
[[redirects]]
  from = "/api/*"
  to = "https://your-fastapi-backend-url.com/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

# Fallback for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200